### ISSUE TITLE
Feature request: Option to disable certain activities from displaying

### ISSUE THREAD

**Issue by Andre601** [PuneetGopinath/github-activity-readme#8]
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**
You can't really disable any activity to be displayed, which in cases like commenting on discussions can result in your recent activities only being comments and nothing else.

**Describe the solution you'd like**
There should be settings to enable or disable the different action types that the GitHub Action should display.
Can be `with` boolean options that aren't required and by default are set to true, which means they should be displayed in the recent activities.

**Describe alternatives you've considered**
Use forks like https://github.com/Techno-Disaster/github-activity-readme that remove a particular activity type, which can be limiting.

**Additional context**

**Comment by PuneetGopinath** [comment]
Nice request, Please wait!!
